name: Build prebuilt binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build NodeJS binaries on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{inputs.node-version}}
      - name: Install dependencies
        run: npm ci --omit peer --omit optional
      - name: Build x64 binary
        run: npm x -- prebuildify --strip --arch x64 --target 20.9.0
      - name: Build arm64 binary
        run: npm x -- prebuildify --strip --arch arm64 --target 20.9.0
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          path: prebuilds/**
          name: prebuilds-${{runner.os}}
          retention-days: 2
  package:
    name: Publish NodeJS package
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/${{github.event.repository.name}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: prebuilds
          pattern: prebuilds-*
          merge-multiple: true
      - name: Check binaries
        run: tree prebuilds
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
